[package]
name = "konsider_api"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "konsider_api"
path = "src/main.rs"

[dependencies]
axum = "0.7.5"
tokio = { version = "1.39.2", features = ["full"] }

