[server]
port = 8080
host = "127.0.0.1"
environment = "local"
origin = "localhost"
jwt_secret = "T7O5aKbBIJyxvrqNxl64W+xVDS5PN0oHlrc84edDdcY="

[log]
retention_days = 1

[database]
user = "k6r_user"
password = "password"
database = "k6r"
# Currently not being used
db_host = "127.0.0.1"
db_port = 5432
require_ssl = false
