[server]
port = 8080
host = "127.0.0.1"
jwt_secret = "T7O5aKbBIJyxvrqNxl64W+xVDS5PN0oHlrc84edDdcY="

[database]
user = "k6r_user"
password = "password"
database = "k6r"
host = "127.0.0.1"
db_port = 5432
require_ssl = false
