[package]
name = "k6r"
version = "0.1.0"
authors = ["Huseen Munye"]
edition = "2021"

[lib]
name = "k6r"
path = "src/lib.rs"

[[bin]]
name = "k6r"
path = "src/main.rs"

[dependencies]
axum = "0.7.7"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
tokio = { version = "1.41.1", features = ["full"] }

[dev-dependencies]
reqwest = "0.12.9"
