name: API CI

on:
  push:
    paths:
      - "prototype_v3/api/**"
  pull_request:
    paths:
      - "prototype_v3/api/**"

env:
  CARGO_TERM_COLOR: always
  SQLX_VERSION: 0.8.0
  SQLX_FEATURES: "rustls,postgres"

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
         - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install sqlx-cli
        working-directory: prototype_v3/api
        run:
            cargo install sqlx-cli
            --version=${{ env.SQLX_VERSION }}
            --features ${{ env.SQLX_FEATURES }}
            --no-default-features
            --locked
      - name: Install postgresql-client
        working-directory: prototype_v3/api
        run: sudo apt-get update && sudo apt-get install postgresql-client -y
      - name: Migrate Database
        working-directory: prototype_v3/api
        run: SKIP=true ./scripts/init_db.sh
      - name: Run Tests
        working-directory: prototype_v3/api
        run: cargo test --all-features

  fmt:
    name: Formating
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Enforce Formatting
        working-directory: prototype_v3/api
        run: cargo fmt --all -- --check

  clippy:
    name: Linting
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
         - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install sqlx-cli
        working-directory: prototype_v3/api
        run:
            cargo install sqlx-cli
            --version=${{ env.SQLX_VERSION }}
            --features ${{ env.SQLX_FEATURES }}
            --no-default-features
            --locked
      - name: Install postgresql-client
        working-directory: prototype_v3/api
        run: sudo apt-get update && sudo apt-get install postgresql-client -y
      - name: Migrate Database
        working-directory: prototype_v3/api
        run: SKIP=true ./scripts/init_db.sh

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Lint Code
        working-directory: prototype_v3/api
        run: cargo clippy -- -D warnings
