name: API CI

on:
  push:
    paths:
      - "api/**"
  pull_request:
    paths:
      - "api/**"

env:
  CARGO_TERM_COLOR: always

  SQLX_VERSION: 0.8.0
  SQLX_FEATURES: "rustls,postgres"

  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: "konsider"

  POSTGRES_HOST: "127.0.0.1"
  POSTGRES_PORT: 5432

  REDIS_HOST: "127.0.0.1"
  REDIS_PORT: 6379

  REDIS_PASSWORD: "password"

  SERVER_HOST: "127.0.0.1"
  SERVER_PORT: 8000

  DATABASE_URL: "postgres://postgres:password@127.0.0.1:5432/konsider"

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Install sqlx-cli
        working-directory: api
        run: cargo install sqlx-cli
          --version=${{ env.SQLX_VERSION }}
          --features ${{ env.SQLX_FEATURES }}
          --no-default-features
          --locked

      - name: Install postgresql-client
        working-directory: api
        run: sudo apt-get update && sudo apt-get install postgresql-client -y

      - name: Migrate Database
        working-directory: api
        run: SKIP=true ./scripts/init_db.sh

      - name: Run Tests
        working-directory: api
        run: cargo test --all-features

  fmt:
    name: Formating
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Enforce Formatting
        working-directory: api
        run: cargo fmt --all -- --check

  clippy:
    name: Linting
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Install sqlx-cli
        working-directory: api
        run: cargo install sqlx-cli
          --version=${{ env.SQLX_VERSION }}
          --features ${{ env.SQLX_FEATURES }}
          --no-default-features
          --locked

      - name: Install postgresql-client
        working-directory: api
        run: sudo apt-get update && sudo apt-get install postgresql-client -y

      - name: Migrate Database
        working-directory: api
        run: SKIP=true ./scripts/init_db.sh

      - name: Lint Code
        working-directory: api
        run: cargo clippy -- -D warnings
